### PR TITLE
chore: Use gradle as the build tool

### LINKED ISSUE #11: How about use gradle as the build tool?
Gradle with kotlin dsl is a good choice,  any plains to use `Gradle` instead of  `Maven` ? 

I can send a PR :-)

### PR DESCRIPTION
**Pull request by blling**
Close #11

### CODE REVIEW

**Comment by blling** [comment]
@hdimitrieski It is ok for review

**Comment by hdimitrieski** [comment]
@blling Thank you for the PR! I will check it out as soon as I can.

**Comment by blling** [comment]
> 

Thanks,  waiting for you :-)

**Comment by blling** [comment]
ping @hdimitrieski :-)

**Comment by hdimitrieski** [comment]
@blling Can you just please see the two comments on the PR? It would be nice if we can fix them before we merge it. :)

**Comment by blling** [comment]
> @blling Can you just please see the two comments on the PR? It would be nice if we can fix them before we merge it. :)

I am sorry, i could not see the comments, where are they ? @hdimitrieski

**Comment by hdimitrieski** [comment]
> 
Here in the PR, I'll try to ping you in each of them and we'll see what happens.

image

**Comment by blling** [comment]
> > 
> 
> Here in the PR, I'll try to ping you in each of them and we'll see what happens.
> 
> image

OK, I don`t know why i chould not see it :-(

**Comment by hdimitrieski** [comment]
> > > 
> > 
> > 
> > Here in the PR, I'll try to ping you in each of them and we'll see what happens.
> > image
> 
> OK, I don`t know why i chould not see it :-(

@blling No problem, I should've tagged you In those comments... :)

**Review by hdimitrieski — APPROVED** [review]
@blling Thanks again for the PR! It looks great.  :)

**Pull request merged**
